@BibleApi_HostAddress = http://localhost:5080

GET {{BibleApi_HostAddress}}/api/Bible/Books
Accept: application/json

### GET Book by Id
GET {{BibleApi_HostAddress}}/api/Bible/Books/1
Accept: application/json


### GET Book by Id
GET {{BibleApi_HostAddress}}/api/Bible/Books/66
Accept: application/json